### ISSUE TITLE
Where is the .env file?

### ISSUE THREAD

**Issue by DrMemoryFish** [navopw/whatsapp-chatgpt#1]
sorry, im having trouble finding the .env file. 
thank you

**Comment by navopw** [comment]
Hello @DrMemoryFish,

you have to create the .env file and add the session token from ChatGPT.

```
SESSION_TOKEN=your_session_token
PREFIX_ENABLED=true
```

Here is a guide on how to find the session token:
https://github.com/transitive-bullshit/chatgpt-api#session-tokens

**Comment by navopw** [comment]
You just name it `.env`.

Since im using the https://www.npmjs.com/package/dotenv package, it searches exactly for that file name.

**Comment by DrMemoryFish** [comment]
> You just name it `.env`.
> 
> Since im using the https://www.npmjs.com/package/dotenv package, it searches exactly for that file name.

Thank you very much 😊
