### ISSUE TITLE
i get this error when scanning the QR code

### ISSUE THREAD

**Issue by HappySama** [navopw/whatsapp-chatgpt#11]
<img width="957" alt="image" src="https://user-images.githubusercontent.com/75913039/211948259-61424461-5ca7-4078-b24a-c8dbc1410232.png">

i don't have any big experience in coding or anything, is there a fix?

**Comment by ycryptx** [comment]
Seems to be discussed here: https://github.com/pedroslopez/whatsapp-web.js/issues/1920

**Comment by navopw** [comment]
Thank you very much @ycryptx

**Comment by navopw** [comment]
Check the newest version, this project now works with OPENAI_API_KEY and not EMAIL & PASSWORD anymore.

You can create a API Key here: https://platform.openai.com/account/api-keys

Also check the latest README: https://github.com/navopw/whatsapp-chatgpt/blob/master/README.md
