### ISSUE TITLE
Error after Inactivity

### ISSUE THREAD

**Issue by crwals-feko** [navopw/whatsapp-chatgpt#19]
I installed and set up the bot correctly. It also works perfectly. Now I wanted to keep the bot accessible 24/7 and put it on my server. After a period of inactivity, the bot stops responding and throws an error. Does anyone have any idea how I can get around this so that I can message the bot 24/7?

**Comment by navopw** [comment]
Hey @crwals-feko,

there is a new method on accessing the chatgpt api.

I will update the whatsapp bot soon.

**Comment by navopw** [comment]
The new method doesn't use any browser hacks and will allow you to run it 24/7 easily.

**Comment by navopw** [comment]
Check the newest version, this project now works with OPENAI_API_KEY and not EMAIL & PASSWORD anymore.

You can create a API Key here: https://platform.openai.com/account/api-keys

Also check the latest README: https://github.com/navopw/whatsapp-chatgpt/blob/master/README.md
