### ISSUE TITLE
 Failed to authenticate with the ChatGPT API ,ChatGPT failed to refresh auth token

### ISSUE THREAD

**Issue by PhilMata** [navopw/whatsapp-chatgpt#2]
My concern about this is not very clear to be fair! What is the problem with these API Token?

**Comment by navopw** [comment]
Hello @PhilMata,

this problem occurs when the session token expires. This happens after some time.

You have to get a new one and put it into the .env file.

```
SESSION_TOKEN=your token
PREFIX_ENABLED=true
```

Here is how to find the session token: https://github.com/transitive-bullshit/chatgpt-api#session-tokens

Let's hope an official API will release soon, so we won't have this problem anymore.

**Comment by PhilMata** [comment]
I actually thought may be I have to create another account for openAI that maybe I will get a working Token....but nothing worked!! after we chat , me and you yesterday through Discord it was working very well, but today morning it was not working...lets hope for the best....One last thing [ADD ME AS A FRIEND AGAIN]

**Comment by navopw** [comment]
:exclamation: OpenAI added some additional Cloudflare protections that are preventing access token refresh.

`whatsapp-chatgpt` now needs a `CLEARANCE_TOKEN` in the `.env` file to work properly.
Check the README file for more information on how to obtain.

Also big thanks to @transitive-bullshit#4414 & contributors for providing a fast fix.

https://github.com/navopw/whatsapp-chatgpt
