### ISSUE TITLE
Error 429

### ISSUE THREAD

**Issue by Adm-ctrl** [navopw/whatsapp-chatgpt#20]
Please translate it to English. Thank you for your great work in advance! Once I send a request with !gpt, I receive the response 

"An error occurred, please contact the administrator. (ChatGPTAPI error 429)". 

I immediately asked ChatGPT about the error message and received the response that too many requests were made. Well, the openai account is new and only four chats have been started with it. Any ideas?

`[Whatsapp ChatGPT] Client is ready!
[Whatsapp ChatGPT] Received prompt from 492212123456799@c.us: Wie viele Zeitzonen gibt es?
An error occured ChatGPTError: ChatGPTAPI error 429
    at ChatGPTAPIBrowser.sendMessage (file:///C:/Users/adm/whatsapp-chatgpt/node_modules/chatgpt/src/chatgpt-api-browser.ts:563:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at handleMessage (C:\Users\adm\whatsapp-chatgpt\src\index.ts:48:22)
    at Client.<anonymous> (C:\Users\adm\whatsapp-chatgpt\src\index.ts:36:9) {
  statusCode: 429,
  statusText: ''
}`

**Comment by navopw** [comment]
I also had this several times. Could be because chatgpt is overloaded sometimes.

There is a new way to access the chatgpt api.

I will release a new version soon, hope it will fix your issue.

**Comment by Adm-ctrl** [comment]
thx a lot bro

**Comment by dhevsabharish** [comment]
@Adm-ctrl Can u please tell me how u opened the bot. i think i got it to work since i reached the line: [Whatsapp ChatGPT] Client is ready! (ss attached)

But i do not know how to move from there. The login was successful anol but idk how to access the bot from here. i searched thru my contacts list.. but i couldn't find any bot at all.

Any help is appreaciated!!

![image](https://user-images.githubusercontent.com/81457271/218723073-418e4415-367c-43fc-8573-d0a5c2ee2da9.png)

**Comment by Adm-ctrl** [comment]
> @Adm-ctrl Can u please tell me how u opened the bot. i think i got it to work since i reached the line: [Whatsapp ChatGPT] Client is ready! (ss attached)
> 
> But i do not know how to move from there. The login was successful anol but idk how to access the bot from here. i searched thru my contacts list.. but i couldn't find any bot at all.
> 
> Any help is appreaciated!!
> 
> ![image](https://user-images.githubusercontent.com/81457271/218723073-418e4415-367c-43fc-8573-d0a5c2ee2da9.png)

You need to message your account from another WhatsApp account. I asked my wife to send me a message. If someone messages you, for example: !gpt Who was first on Earth, the chicken or the egg. Just as an example.

**Comment by navopw** [comment]
Check the newest version, this project now works with OPENAI_API_KEY and not EMAIL & PASSWORD anymore.

You can create a API Key here: https://platform.openai.com/account/api-keys

Also check the latest README: https://github.com/navopw/whatsapp-chatgpt/blob/master/README.md

**Comment by bhavnasiyeshvant** [comment]
adding a payment details to my account and waiting for 10 mins to restart the service fixed error

**Comment by belqit** [comment]
![image](https://user-images.githubusercontent.com/44238749/230046713-871d1292-3571-4480-bc7e-90b578edad68.png)
this was the problem for me
