### ISSUE TITLE
[Whatsapp ChatGPT] Failed to authenticate with the ChatGPT API: No element found for selector: button[type="submit"]

### ISSUE THREAD

**Issue by thatsankur** [navopw/whatsapp-chatgpt#21]
I Followed the instruction and got following issue after npm run start

[Whatsapp ChatGPT] Failed to authenticate with the ChatGPT API: No element found for selector: button[type="submit"]

It went till email and password screen but after entering password it stopped the process with above error.

**Comment by navopw** [comment]
Could be that it's currently broken. I will bring an update out soon.

**Comment by sonawanesuraj9** [comment]
Any update on this?

**Comment by navopw** [comment]
Check the newest version, this project now works with OPENAI_API_KEY and not EMAIL & PASSWORD anymore.

You can create a API Key here: https://platform.openai.com/account/api-keys

Also check the latest README: https://github.com/navopw/whatsapp-chatgpt/blob/master/README.md
