### ISSUE TITLE
ChatGPTAPI error 400

### ISSUE THREAD

**Issue by chevaleresque** [navopw/whatsapp-chatgpt#23]
How to solve ChatGPTAPI error 400 ?

**Comment by chevaleresque** [comment]
![error](https://user-images.githubusercontent.com/124043929/217486602-1b460854-dd77-4cd0-bcbf-de0bcc3cd28a.JPG)

**Comment by navopw** [comment]
Check the newest version, this project now works with OPENAI_API_KEY and not EMAIL & PASSWORD anymore.

You can create a API Key here: https://platform.openai.com/account/api-keys

Also check the latest README: https://github.com/navopw/whatsapp-chatgpt/blob/master/README.md
