### ISSUE TITLE
Issue when i authenticate using google in chat.openai.com

### ISSUE THREAD

**Issue by siulynot** [navopw/whatsapp-chatgpt#26]
When i authenticate using google in chatgpt, it seems like it does not recognize the login and wont redirect me to whatsapp. It stays stuck or something wont process the next step, not sure.

**Comment by navopw** [comment]
Check the newest version, this project now works with OPENAI_API_KEY and not EMAIL & PASSWORD anymore.

You can create a API Key here: https://platform.openai.com/account/api-keys

Also check the latest README: https://github.com/navopw/whatsapp-chatgpt/blob/master/README.md
