### ISSUE TITLE
(ChatGPTAPI error 429)

### ISSUE THREAD

**Issue by watzapnet** [navopw/whatsapp-chatgpt#3]
Everything works great. I got a reply for the first message but for the rest i get the following error as a reply. 

"An error occured, please contact the administrator. (ChatGPTAPI error 429)"

Any fix would be appreciated..

**Comment by azwarbahar** [comment]
I asked the same thing a few days ago on discord, and someone suggested modifying the sample code using a different API Key so you don't get a limit.
I don't know how to modify it, but that answer was given to me

**Comment by watzapnet** [comment]
> I asked the same thing a few days ago on discord, and someone suggested modifying the sample code using a different API Key so you don't get a limit. I don't know how to modify it, but that answer was given to me

There's no API KEY needed. It just autologin with using chroimium bundle. First message is ok but the rest i get the error 429

**Comment by navopw** [comment]
I'll check it out.

**Comment by andresssantos** [comment]
Same problem here.

**Comment by doofzoff** [comment]
Yep, same. Help please with it.

**Comment by doofzoff** [comment]
> I'll check it out.

Can you help us with that problem? Pls.

**Comment by cprieto64** [comment]
Error 429 here too..

**Comment by navopw** [comment]
This will happen if you're you're calling into the ChatGPT API too often.

Error Code 429 means Too Many Requests.

Try to start it again.

I now also updated this project to the latest version of the chatgpt api I'm using.
