### ISSUE TITLE
Error 403 

### ISSUE THREAD

**Issue by shubham-garg1** [navopw/whatsapp-chatgpt#8]
Authentication was successful but its not working.

Whatsapp Reply:

An error occured, please contact the administrator. (ChatGPTAPI error 403)

Terminal:

[Whatsapp ChatGPT] Client is ready!
[Whatsapp ChatGPT] Received prompt from `<mynumber>`@c.us: hi

**Comment by Omar-Alodwan** [comment]
i get the same error did you find any fix for it?

**Comment by navopw** [comment]
Please try again with the latest version of this project.

**Comment by chevaleresque** [comment]
same issue, i already used the latest version of this project

**Comment by navopw** [comment]
Check the newest version, this project now works with OPENAI_API_KEY and not EMAIL & PASSWORD anymore.

You can create a API Key here: https://platform.openai.com/account/api-keys

Also check the latest README: https://github.com/navopw/whatsapp-chatgpt/blob/master/README.md

If this error still occurs, please open a new issue.
